### ISSUE TITLE
Improve serverless.yml / cloudformation stacks across services

### ISSUE THREAD

**Issue by zhammer** [zhammer/morning-cd#108]
Ideally the entire morning cd collection of services could be totally redeployed directly from their serverless.yml files. A few current issues / opportunities for improvement

- [ ] Some services had manual actions performed from console that could be included in their cloudformation
- [ ] Some services have messy, hard-coded values where cloudformation intrinsic functions could be used
  * referring to references within their stack, or
  * referring to values that could be imported from other stacks (like sns topics)
- [ ] Some services have big chunks of serverless.yml config that could be extracted into sub files for clarity
- [ ] Some services had manual actions performed that couldnt _easily_ (or at all) be included in their cloudformation *these can be ignored at first*

It'd be nice to do some cleanup on this overtime. Learning better cloudformation setup (via serverless) would be nice overall too

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html

**Comment by zhammer** [comment]
change sunlight service name to `morning-cd-sunlight` https://github.com/zhammer/morning-cd-sunlight/blob/master/serverless.yml

**Comment by zhammer** [comment]
- morning-cd-front ✅ 
- morning-cd-listens
  - [ ] change name to `morning-cd-listens` from `listens`
  - [ ] add db to stack
- morning-cd-sunlight
  - [ ] change name to `morning-cd-sunlight` from `sunlight`
- morning-cd-playlists
  - [ ] AddToPlaylistQueue subscription endpoint get from resources
  - [ ] AddToPlaylistQueue topicArn import value from listens stack
  - [ ] add db to stack
